# Ноутбук для решения задач урока 2.2 - Pandas забудь про циклы!

In [4]:
import pandas as pd

Стэпы 4 и 7

In [ ]:
# для тестирования шагов 4,7
path = 'https://raw.githubusercontent.com/a-milenkin/Competitive_Data_Science/main/data/driver_info.csv'
driver_info = pd.read_csv(path)

In [ ]:
driver_info.head()

,age,user_rating,user_rides,user_time_accident,user_id,sex,first_ride_date
0,27,9.0,865,19.0,l17437965W,1,2019-4-2
1,46,7.9,2116,11.0,Z12362316j,0,2021-11-19
2,59,7.8,947,4.0,g11098715c,0,2021-1-15
3,37,7.0,18,4.0,U12618125q,0,2019-11-20
4,39,8.2,428,7.0,A14375829B,0,2019-7-23

In [ ]:
driver_info['user_time_accident'].value_counts()

6.0     843
3.0     794
8.0     777
4.0     760
11.0    752
       ...
82.0      1
85.0      1
84.0      1
80.0      1
83.0      1
Name: user_time_accident, Length: 84, dtype: int64

In [ ]:
driver_info['age'].median()

33.0

In [ ]:
driver_info.describe()

,age,user_rating,user_rides,user_time_accident,sex
count,15153.000000,15153.000000,15153.000000,14182.000000,15153.000000
mean,33.581073,8.109345,871.015442,10.129601,0.499967
std,9.919271,0.668246,573.512378,8.867482,0.500016
min,18.000000,5.800000,0.000000,0.000000,0.000000
25%,25.000000,7.700000,421.000000,4.000000,0.000000
50%,33.000000,8.100000,876.000000,9.000000,0.000000
75%,41.000000,8.600000,1145.000000,14.000000,1.000000
max,63.000000,10.000000,3316.000000,86.000000,1.000000

Стэпы 6 и 13

In [ ]:
# Для тестирования шагов 6, 13
headers = ['user_id','car_id','ride_id','ride_date','rating','ride_duration','ride_cost','speed_avg','speed_max','stop_times','distance','refueling','user_ride_quality','deviation_normal']
data1 = [['q53527020Q','g55775125g','i1O','2020-01-16',3.42,33,324,75,100.29813514676134,0,2412.859858364817,0,-3.828165817447904,-12.577],
['X72952203K','Y-6420899e','Z1i','2020-01-19',4.0,65,839,51,78.0,0,2553.2839709438263,0,-0.1661988045307138,-5.85],
['g40994147T','z77468044J','x1M','2020-01-21',6.18,46,363,47,73.0,2,207.99309441034063,0,-6.904072336062649,0.0],
['E18650750E','W50413234I','W1Y','2020-03-17',1.43,80,955,34,116.0,2,1758.4787326019953,0,3.132158298525006,18.966]]

data2 = [['D18083254C','e-4559210H','U1f','2020-03-21',3.45,142292,2276667,52,64.0,1,7541414.254671801,0,-29.248641469679256,-8.126],
['G12536963g','B61056692H','f1p','2020-02-26',5.73,49,681,36,65.0,1,1633.554568012732,0,5.566720367721429,0.0],
['j17924049w','g10190493K','e1F','2020-03-15',3.8,33,426,56,121.02952155423937,0,1854.4339064466585,0,-21.87409354475036,-19.996],
['Z21861082q','U-8316679F','s1l','2020-02-22',2.88,23,685,53,58.0,0,1290.3012366594276,0,1.181858481684772,-0.799],
['w32247420J','I-2277714Y','t1N','2020-02-08',0.1,168,8397,66,116.0,2,5049.357084205007,0,-7.047227923552489,16.841]]

df1 = pd.DataFrame(data1, columns = headers)
df2 = pd.DataFrame(data2, columns = headers)

In [ ]:
# добавьте данные для тестов
car_black_list = ['Y-6420899e']
user_white_list = ['q53527020Q']
cols2drop = []

In [ ]:
pd.concat([df1, df2])

,user_id,car_id,ride_id,ride_date,rating,ride_duration,ride_cost,speed_avg,speed_max,stop_times,distance,refueling,user_ride_quality,deviation_normal
0,q53527020Q,g55775125g,i1O,2020-01-16,3.42,33,324,75,100.298135,0,2.412860e+03,0,-3.828166,-12.577
1,X72952203K,Y-6420899e,Z1i,2020-01-19,4.00,65,839,51,78.000000,0,2.553284e+03,0,-0.166199,-5.850
2,g40994147T,z77468044J,x1M,2020-01-21,6.18,46,363,47,73.000000,2,2.079931e+02,0,-6.904072,0.000
3,E18650750E,W50413234I,W1Y,2020-03-17,1.43,80,955,34,116.000000,2,1.758479e+03,0,3.132158,18.966
0,D18083254C,e-4559210H,U1f,2020-03-21,3.45,142292,2276667,52,64.000000,1,7.541414e+06,0,-29.248641,-8.126
1,G12536963g,B61056692H,f1p,2020-02-26,5.73,49,681,36,65.000000,1,1.633555e+03,0,5.566720,0.000
2,j17924049w,g10190493K,e1F,2020-03-15,3.80,33,426,56,121.029522,0,1.854434e+03,0,-21.874094,-19.996
3,Z21861082q,U-8316679F,s1l,2020-02-22,2.88,23,685,53,58.000000,0,1.290301e+03,0,1.181858,-0.799
4,w32247420J,I-2277714Y,t1N,2020-02-08,0.10,168,8397,66,116.000000,2,5.049357e+03,0,-7.047228,16.841

In [ ]:
# Соединить эти две таблицы вместе.
df = pd.concat([df1.iloc[::2], df2.iloc[::2]])
# Оставить только строки, где rating > 4 и stop_times равен 2, 3 или 5.
k1 = [2, 3, 5]
mask = df['stop_times'].isin(k1)
df = df[mask]
df = df[df['rating'] > 4]
# В получившемся датафрейме оставить только те строки, где car_id не входит в список car_black_list и user_id входит в список user_white_list.
df = df[~df['car_id'].isin(car_black_list)]
df = df[~df['user_id'].isin(user_white_list)]
# Итоговый объект pd.DataFrame() поместить в переменную result.
result = df

In [ ]:
df.head()

,user_id,car_id,ride_id,ride_date,rating,ride_duration,ride_cost,speed_avg,speed_max,stop_times,distance,refueling,user_ride_quality,deviation_normal
2,g40994147T,z77468044J,x1M,2020-01-21,6.18,46,363,47,73.0,2,207.993094,0,-6.904072,0.0

Шаг 7: Сколько водителей имеет количество инцидентов (user_time_accident) на полуинтервале (4.5, 9.0] и age < 40?

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Dimon/Again/2_Классические_элементы/2_Pandas/data_driver_info.csv')

In [ ]:
df = df[(df['user_time_accident'] > 4.5) & (df['user_time_accident'] <= 9) & (df['age'] < 40)]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2478 entries, 4 to 15151
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   age                 2478 non-null   int64
 1   user_rating         2478 non-null   float64
 2   user_rides          2478 non-null   int64
 3   user_time_accident  2478 non-null   float64
 4   user_id             2478 non-null   object
 5   sex                 2478 non-null   int64
 6   first_ride_date     2478 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 154.9+ KB

Стэпы 8

In [5]:
# Для тестирования шагов 8, 14
headers = ['age','user_rating','user_rides','user_time_accident','user_id','sex','first_ride_date']
data = [[24,7.4,630,0.0,'k10444942s',1,2020-7-25],
[38,8.1,1035,2.0,'h19096602M',0,2019-2-16],
[26,8.2,617,7.0,'Q15734607H',1,2020-7-22],
[44,8.8,697,7.0,'l15409162f',0,2019-5-14],
[30,8.4,335,43.0,'A17982529a',1,2019-8-18]]

df = pd.DataFrame(data, columns = headers)

In [ ]:
df['tripple_accident'] = df['user_time_accident'] * 3
df['rides_on_ratin'] = df.user_rides / df.user_rating
df = df[df['user_time_accident'] > 25]
df = df[df.age > df.age.mean()]

Стэпы 9

In [ ]:
# Добавьте новую строку (с индексом new_index:(int / str) и значениями new_data:list).
df.loc[new_index] = new_data
# Удалите строки с индексами из списка del_index_list: list.
df = df.drop(index=del_index_list)
# Увеличьте значение destroy_degree на 1 в строке с индексом равным index. Переменная index содержит индекс строки ИЛИ число (индекс).
df.loc[index]['destroy_degree'] += 1
# Удалите столбец fix_date, т.к. не стоит сейчас думать о времени.
df.drop('fix_date', axis= 1 , inplace=True)
# Создайте новый столбец efficient, который равен destroy_degree деленный на work_duration.
df['efficient'] = df['destroy_degree'] / df['work_duration']
# Возведите столбец work_duration в квадрат.
df['work_duration'] = df['work_duration'] ** 2
# Переименуйте столбец work_duration в work_duration_square.
df.rename(columns = {'work_duration':' work_duration_square'}, inplace = True)
# Удалите дубликаты по столбцу car_id.
df.drop_duplicates(subset='car_id', inplace=True)

Стэп 10

In [ ]:
# Для тестирования шага 10
path = 'https://raw.githubusercontent.com/a-milenkin/Competitive_Data_Science/main/data/fix_info.csv'
df = pd.read_csv(path)

Стэп 11

In [ ]:
# Для тестирования шага 11
headers = ['car_id','model','car_type','fuel_type','car_rating','year_to_start','riders','year_to_work','target_reg','target_class']
data = [['y13744087j','Kia Rio X-line','economy','petrol',3.78,2015,76163,2021,108.53,'another_bug'],
['O41613818T','VW Polo VI','economy','petrol',3.9,2015,78218,2021,35.2,'electro_bug'],
['d-2109686j','Renault Sandero','standart','petrol',6.3,2012,23340,2017,38.62,'gear_stick'],
['u29695600e','Mercedes-Benz GLC','business','petrol',4.04,2011,1263,2020,30.34,'engine_fuel'],
['N-8915870N','Renault Sandero','standart','petrol',4.7,2012,26428,2017,30.45,'engine_fuel']]

df = pd.DataFrame(data, columns = headers)

# добавьте сами нужные значения
sort_by_list = ['model', 'car_type']
columns_order_list = []
cols2drop = []
critical_car_rating = 4

In [ ]:
# Отсортируйте строки сначала по убыванию 1-го столбца из списка sort_by_list, затем по возрастанию 2-го столбца из списка.
df = df.sort_values(by = sort_by_list, ascending = [False , True])
# Удалите столбцы из списка cols2drop с учетом того, что некоторых столбцов может не быть в df.
df.drop([i for i in cols2drop if i in df.columns], axis= 1, inplace=True)
# Сделайте порядок столбцов в df в соответствии с переменной columns_order_list: List[str].
# df = df[columns_order_list]
# Удалите строки, в которых car_rating < critical_car_rating.
df = df[df['car_rating'] >= critical_car_rating]
# Удалите строки, где число поездок riders больше 10_000, или тип машины car_type относится либо к standart, либо к economy.
mask = df['car_type'].isin(['standart', 'economy'])
df = df[~mask]
df = df[df['riders'] < 10_000]

Стэп 12

In [ ]:
# Для тестирования шага 12

headers = ['car_id','model','car_type','fuel_type','car_rating','year_to_start','riders','year_to_work','target_1','target_2']

data = [['e-1431476C','Renault Kaptur','standart','petrol',4.84,2014,3856,2017,2,'gear_stick'],
['L-6578341x','Renault Sandero','standart','petrol',4.84,2011,54093,2018,0,'engine_check'],
['i11115813c','Skoda Rapid','economy','petrol',4.16,2015,16214,2017,0,'electro_bug'],
['w-1250035f','Kia Rio X-line','economy','petrol',5.3,2015,16948,2017,1,'wheel_shake'],
['E-3430793T','Smart Coupe','economy','petrol',4.54,2015,20430,2014,1,'break_bug'],
['g13538879M','Nissan Qashqai','standart','petrol',4.28,2015,19517,2020,0,'break_bug'],
['g10190493K','Kia Sportage','standart','petrol',3.34,2014,2018,2017,0,'engine_fuel']]

df = pd.DataFrame(data, columns = headers)

In [ ]:
# Запишите в переменную mean_rating среднее по столбцу car_rating .
mean_rating = df.car_rating.mean()
# Увеличьте на один все значения в столбцах car_rating и year_to_work.
df.car_rating = df.car_rating + 1
df.year_to_work = df.year_to_work + 1
# Отфильтруйте любым из удобных способов машины с рейтингом выше среднего от столбца car_rating (используйте переменную mean_rating).
df = df[df['car_rating'] > mean_rating]
# Преобразуйте столбец year_to_work следующим образом: если значение меньше 2017, то прибавьте 2, иначе разделите значение нацело на 5.
df.year_to_work = df.year_to_work.apply(lambda x: x+2 if x < 2017 else x//5)
# Переименуйте столбец year_to_start в new_year_to_start и удалите столбец fuel_type.
df.rename(columns = {'year_to_start':'new_year_to_start'}, inplace = True)
df.drop('fuel_type', axis= 1 , inplace=True)
# Ко всем значениям из столбца car_type добавьте приставку super_ (standart -> super_standart).
df.car_type = df.car_type.apply(lambda x: 'super_' + x)
# Решение запишите в переменную result.
result = df

Степ 13

In [ ]:
# Добавьте столбец flag, который равен 'good_line', если rating > 5 and speed_max < 100.
# 'bad_line', если  rating > 5 and speed_max > 100. 'undefined' в остальных случаях.
df['flag'] = df.apply(lambda x: 'good_line' if x.rating > 5 and x.speed_max < 100 else ('bad_line' if x.rating > 5 and x.speed_max > 100 else 'undefined'), axis=1)
# Добавьте столбец speed_check, который принимает значения 'avg_more', если distance/ride_duration > speed_avg, иначе 'avg_less'.
df['speed_check'] = df.apply(lambda x: 'avg_more' if x.distance/x.ride_duration > x.speed_avg else 'avg_less')
# Удалите столбцы из списка cols2drop.
df.drop([i for i in cols2drop if i in df.columns], axis= 1, inplace=True)
# Удалите строки, в которых car_id имеет пустые значения (только NA удаляем).
mask = df.car_id.isnull()
df = df[~mask]
# Результат запишите в переменную result.
result = df

Степ 14

In [8]:
# Для тестирования шагов 8, 14
headers = ['age','user_rating','user_rides','user_time_accident','user_id','sex','first_ride_date']
data = [[24,7.4,630,0.0,'k10444942s',1,2020-7-25],
[38,8.1,1035,2.0,'h19096602M',0,2019-2-16],
[26,8.2,617,7.0,'Q15734607H',1,2020-7-22],
[44,8.8,697,7.0,'l15409162f',0,2019-5-14],
[30,8.4,335,43.0,'A17982529a',1,2019-8-18]]

df = pd.DataFrame(data, columns = headers)

In [17]:
df.apply(lambda x: x.count(), axis=1)

0    7
1    7
2    7
3    7
4    7
dtype: int64

In [6]:
# Посчитайте количество пропусков в каждой строке и запишите это в новый столбец nans_num.
df['nans_num'] = df.apply(lambda x: x.count(), axis=1)
# Удалите строки, где количество пропусков больше 2.
df = df[df['nans_num'] <= 2]
# Удалите строки, где age имеет пропущенные значения.
mask = df.age.isnull()
df = df[~mask]
# Заполните пропущенные значения в столбце user_time_accident медианным значением.
df.user_time_accident.fillna(df.user_time_accident.median())
# Оставьте только столбцы age, user_rides, user_time_accident.
df = df[['age', 'user_rides', 'user_time_accident']]
# Решение запишите в переменную result.
result = df